[workspace]
members = [
  "src-tauri/core",
  "src-tauri/app-main",
  "src-tauri/app-cli",
  "src-tauri-plugins/tauri-plugin-picker",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "3.0.4"

[workspace.dependencies]
async-trait = "0.1"
base64 = "0.22"
image = "0.24"
kabegame-core = {path = "./src-tauri/core", default-features = false}
tauri-plugin-picker = { path = "./src-tauri-plugins/tauri-plugin-picker" }
rhai = {version = "1.19", features = ["sync"]}
serde = {version = "1.0", features = ["derive"]}
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_json = "1.0"
sha2 = "0.10"
tauri-build = {version = "2.5", features = []}
tokio = {version = "1", features = ["full"]}
url = "2.5"
uuid = {version = "1.6", features = ["v4", "serde"]}
windows-sys = {version = "0.52", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_Storage_FileSystem",
  "Win32_System_Com",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]}
zip = "0.6"

# [profile.release]
# on when release
# codegen-units = 1
# lto = "thin"
