[package]
name = "kabegame"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
kabegame-core = { workspace = true, features = ["tray", "wallpaper", "virtual-drive"] }
tauri = { workspace = true, features = ["protocol-asset"] }
tauri-plugin-dialog = { workspace = true }
tauri-plugin-shell = { workspace = true }
tauri-plugin-fs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
image = { workspace = true }
sha2 = { workspace = true }
uuid = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol", "kabegame-core/custom-protocol"]

[[bin]]
name = "kabegame"
path = "src/main.rs"
