[package]
name = "kabegame"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
kabegame-core = { workspace = true }
tauri = { workspace = true, features = ["protocol-asset"] }
tauri-plugin-dialog = "2.4.2"
tauri-plugin-shell = "2.0"
tauri-plugin-fs = "2.0"
governor = {  version = "0.7", optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
image = { workspace = true }
sha2 = { workspace = true }
uuid = { workspace = true }
lru = { version = "0.12", optional = true }
memmap2 = { version = "0.9", optional = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
winreg = "0.52"
winver = "1"
dokan = {version = "0.3.1", optional = true}
widestring = {version = "0.4.3", optional = true}
winapi = { version = "0.3.9", features = ["ntstatus", "winnt", "winbase"], optional = true }
windows = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_System_Com",
  "Win32_UI_Shell",
] }

[build-dependencies]
tauri-build = { workspace = true }

[features]
default = ["custom-protocol", "tray", "virtual-drive"]
tray = ["dep:governor"]
custom-protocol = ["tauri/custom-protocol", "kabegame-core/custom-protocol"]
virtual-drive = ["dep:dokan", "dep:widestring", "dep:winapi", "dep:lru", "dep:memmap2", "kabegame-core/virtual-drive"]


[[bin]]
name = "kabegame"
path = "src/main.rs"
