[package]
name = "kabegame"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
kabegame-core = { workspace = true, features = ["tray", "wallpaper", "virtual-drive"] }
tauri = { workspace = true, features = ["protocol-asset"] }
tauri-plugin-dialog = "2.0"
tauri-plugin-shell = "2.0"
tauri-plugin-fs = "2.0"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
image = { workspace = true }
sha2 = { workspace = true }
uuid = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_System_DataExchange",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
tauri-build = { workspace = true }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol", "kabegame-core/custom-protocol"]

[[bin]]
name = "kabegame"
path = "src/main.rs"
