[package]
name = "kabegame-cli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
kabegame-core = { workspace = true }
tauri = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
zip = { workspace = true }
base64 = { workspace = true }
url = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[[bin]]
name = "kabegame-cli"
path = "src/main.rs"



