[package]
name = "kabegame-cli"
version.workspace = true
edition.workspace = true

[dependencies]
kabegame-core = { path = "../core" }
tauri.workspace = true
tauri-plugin-shell.workspace = true
tauri-plugin-dialog.workspace = true
tauri-plugin-fs.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true
zip.workspace = true

[build-dependencies]
tauri-build.workspace = true

[[bin]]
name = "kabegame-cli"
path = "src/main.rs"


