[package]
edition = {workspace = true}
name = "kabegame-cli"
version = {workspace = true}

[dependencies]
base64 = {workspace = true}
clap = {version = "4.5", features = ["derive"]}
kabegame-core = {workspace = true, features = ["ipc"]}
serde = {workspace = true}
serde_json = {workspace = true}
tauri = {workspace = true}
tokio = {workspace = true}
url = {workspace = true}
uuid = {workspace = true}
zip = {workspace = true}

[build-dependencies]
tauri-build = {workspace = true}

[features]
# 默认启用 VD：Windows 下可用于提权挂载画册盘（Dokan）。
default = ["virtual-driver"]
virtual-driver = ["kabegame-core/virtual-driver"]

[[bin]]
name = "kabegame-cli"
path = "src/main.rs"
